### ISSUE TITLE
Detecting model (serverside) changes

### ISSUE THREAD

**Issue by vgillestad** [macdevnet/mvvmc-demo#3]
Question: Who should be responsible for detecting model-changes?

In the sample app you display a list of people and their rank. I guess that list does not change to often, but lets say it did. Who would then be responsible for doing these updates/refetches?

Possibility 1: **It's the models responsibility** and it should contain a timer function to periodically do the refetch. But then I guess the model would need a way to notify the viewModel about the update?

Possibility 2: **It's the viewModels responsibility.** If would have a timer function and periodically call the model.items function to update/refetch.

(Of course you could do it easy and put a "refresh" button in the view that the user has to click to get the latest data, but I would like it to be more "event driven")

**Comment by werediver** [comment]
As far as I'm aware of MVVM, there are two approaches to defining a model:
- domain-centric approach says that the model is a domain-model, i.e. incapsulates methods to access the data source (e.g. server), pushing the changes back, and/or doing other domain-specific operations;
- data-centric approach says that the model is a plain old data type without any domain-specific logic incapsulated (thus requiring the view model to handle it all).

But with either approach I don't think the periodic update should be put in the model, because it's unlikely a domain-specific, but rather business-logic / UI level requirement.

**Comment by vgillestad** [comment]
Hi. Thank you for an explanatory answer! Then I guess I will leave it ut to the viewModel to be responsible for it 👍
